steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}", "."]
    env:
      - "ENV=${_ENV}"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push",  "${_IMAGE_NAME}"]
    env:
      - "ENV=${_ENV}"

  - name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]
    env:
      - "ENV=${_ENV}"

  - name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
        "--",
        "python",
        "manage.py",
        "collectstatic",
        "--no-input",
      ]
    env:
      - "ENV=${_ENV}"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image=${_IMAGE_NAME}",
        "--region=${_REGION}",
        "--platform=managed",
      ]
    env:
      - "ENV=${_ENV}"

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: gcr.io/${PROJECT_ID}/${_SERVICE_NAME}
  _REGION: ${_DEPLOY_REGION}
  _ENV: "development"