# Generated by Django 4.1.5 on 2023-01-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_is_active'),
        ('authentication', '0004_alter_customuser_is_active 2'),
    ]

    operations = [
    ]
