# Generated by Django 4.1.5 on 2023-04-01 02:56

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tax_id_new',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, null=True, unique=True),
        ),
    ]
