# Generated by Django 4.1.5 on 2023-04-01 02:57

from django.db import migrations


def custom_task(apps, schema_editor):
    CustomUser = apps.get_model('authentication', 'CustomUser')
    for user in CustomUser.objects.all():
        user.tax_id_new = user.tax_id
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_tax_id_new'),
    ]

    operations = [
        migrations.RunPython(custom_task, lambda apps, schema_editor: None),
    ]
