# Generated by Django 4.1.5 on 2023-04-01 03:04

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_cpf_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tax_id_new',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, unique=True),
        ),
    ]
