# Generated by Django 4.1.5 on 2023-04-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_customuser_tax_id_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tax_id',
        ),
    ]
