# Generated by Django 4.1.5 on 2023-04-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_customuser_tax_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tax_id_new',
            new_name='tax_id',
        ),
    ]
