# Generated by Django 4.1.5 on 2023-03-21 23:44

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_welcomecampaign_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AddField(
            model_name='store',
            name='pos_service',
            field=models.CharField(blank=True, choices=[('dummy', 'dummy')], max_length=30, null=True),
        ),
    ]
