# Generated by Django 4.1.5 on 2023-04-01 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0004_store_api_key_store_pos_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignuser',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.regularcampaign', verbose_name='Campaign'),
        ),
        migrations.AlterField(
            model_name='campaignuser',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='campaignuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='regularcampaign',
            name='item_id',
            field=models.CharField(max_length=100, verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='regularcampaign',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='regularcampaign',
            name='item_qty',
            field=models.IntegerField(verbose_name='Item quantity'),
        ),
        migrations.AlterField(
            model_name='regularcampaign',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='regularcampaign',
            name='reward_id',
            field=models.CharField(max_length=100, verbose_name='Reward ID'),
        ),
        migrations.AlterField(
            model_name='regularcampaign',
            name='reward_name',
            field=models.CharField(max_length=100, verbose_name='Reward name'),
        ),
        migrations.AlterField(
            model_name='regularcampaign',
            name='reward_qty',
            field=models.IntegerField(verbose_name='Reward quantity'),
        ),
        migrations.AlterField(
            model_name='store',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='API key')),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='pos_service',
            field=models.CharField(blank=True, choices=[('dummy', 'dummy')], max_length=30, null=True, verbose_name='POS service'),
        ),
        migrations.AlterField(
            model_name='welcomecampaign',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='welcomecampaign',
            name='reward_id',
            field=models.CharField(max_length=100, verbose_name='Reward ID'),
        ),
        migrations.AlterField(
            model_name='welcomecampaign',
            name='reward_name',
            field=models.CharField(max_length=100, verbose_name='Reward name'),
        ),
        migrations.AlterField(
            model_name='welcomecampaign',
            name='reward_qty',
            field=models.IntegerField(verbose_name='Reward quantity'),
        ),
        migrations.AlterField(
            model_name='welcomecampaign',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stores.store', verbose_name='Store'),
        ),
    ]
